.TH "MAN UEL" 1 "13 JUNE 2011"

                  __.ccc.,
               __/$$AA$$$$$$Azz._
           _,cc$$$$$$$$$$$$$$$$$$o   VIVA LA
          /$$$$$$$$$$$$$$$$$$$$$$$Az.   REVOLUTION!
        .A$$$$$$$$$$V'     ($$$$$$$$$$)
       ($$$$$$$VU            `($$$$$$$$$A
      \\$$$$$$$U/              ($$$$$$$$$$|
       )$$$$$$/ '''`     '```  \\$$$$$$$$$$|
      /$$$$$$/  (.)       (.)  \\$$$$$$$$$|
     ($$$$$$$|                  |$$$$$$$$$|
      \\$$$$$$\\         >        |$$$$$$$$$$\\
       \\$$$$$$\\                 |$$$$$$$$$
     |$$$$$$$$\\     -____       /$$$$$$$
      `GGG$$$GG'               \\GGGGGGd'
                                
.SH NAME
Manuel

.SH SYNOPSIS
\fBmanuel\fp [ --party | --code ] ...

.SH DESCRIPTION
When not hacking at Twilio, Manuel can be found jailingbreaking 
his kindle, installing KDE on Windows in a VM, causing trouble 
with git-svn, giving relationship advice on reddit, spreading
HD-DVD encryption keys, speeding in a Pontiac Trans Am and 
purchasing leather jackets.

.SH "SEE ALSO"
git-svn(3), valgrind(3)
